### ISSUE TITLE
Hopper pipe or chest pipe

### ISSUE THREAD

**Issue by wi-ta** [tcooc/AdditionalPipesBC#118] opened 2015-06-03 09:29 UTC
Heya Jamie
Is there a way to make a pipe that does pull items like a hopper?
Recipe: Hopper - Glas - Hopper = 2x Hopper pipe
Or as an alternative a pipe that does act like a chest so the hopper can drop items in the pipe.

greetings
wilfried

**Comment by multiplemonomials** [comment] 2015-06-06 21:39
..?  
What do you mean pulls items "like a hopper?" The obsidian pipe sucks in items that touch it, if that's what you mean.

**Comment by wi-ta** [comment] 2015-06-06 21:50
No :-)

Now i pull out items ot of the machines with a hopper in a chest 
From the chest with a woodpipe and redstonemotor in the pipesystem.
It would be nice if a pipe can pull items out of a machine like a hopper.

**Comment by multiplemonomials** [comment] 2015-06-06 21:58
You mean that it would suck out items from the bottom of a machine without power?

**Comment by wi-ta** [comment] 2015-06-06 22:38
Yes like a hopper.
but only removing items

**Comment by wi-ta** [comment] 2015-06-06 22:38
ups wrong butten

**Comment by wi-ta** [comment] 2015-06-07 10:30
If this is to complicated would it be possible to have a pipe that does connect to a hopper?

**Comment by multiplemonomials** [comment] 2015-06-10 02:19
Why can't you just use a wooden pipe?

**Comment by wi-ta** [comment] 2015-06-10 11:13
20 or more machines with wooden pipe and redstonemotor are lagging like hell
That is why i did switch to hopper and no lag at all

I can see you dont like the idea that is ok
thank you for your time 
cya

**Comment by multiplemonomials** [comment] 2015-06-10 13:43
Don't overreact.  I was just trying to figure out exactly what this pipe would be used for, because I wasn't exactly sure.  I'm still going to make it.

**Comment by wi-ta** [comment] 2015-06-10 13:54
I'm not overreacting XD
i just had the impression you don't like it at all
annyway ...
if it is more comfortable or easier for you , a pipe that does connect to a hopper would do also the job

**Comment by multiplemonomials** [comment] 2015-06-10 16:26
Alright, can you try [this build](https://www.dropbox.com/s/40pddsvxjhwirln/additionalpipes-4.6.0.jar?dl=0)?  It's called the Gravity Feed Pipe.  It turns out that the code to make an automatic pull pipe was pretty much the same as the code to make a pipe that worked with hoppers.  So, I made a pipe which pulls one item out of the inventory above it every 48 ticks.

**Comment by wi-ta** [comment] 2015-06-10 16:51
Give some minutes to test

**Comment by wi-ta** [comment] 2015-06-10 16:53
BuildCraft 7.0.8 and Compat 7.0.7  
?

**Comment by wi-ta** [comment] 2015-06-10 17:45
i just did a test with only Buildcraft and some lib 

The Gravity Feed Pipe is really cool better then expected
i will try now with other mods (placing one by one) to see what is going on.

**Comment by wi-ta** [comment] 2015-06-10 18:31
crash with Forestry_1.7.10-3.5.6.15.jar

**Comment by wi-ta** [comment] 2015-06-10 19:11
Not working like it should :-(
![2015-06-10_21 09 20](https://cloud.githubusercontent.com/assets/11215905/8091631/3b288d54-0fb5-11e5-84b8-e612b9417f25.png)

**Comment by wi-ta** [comment] 2015-06-10 19:28
the same on Railcraft 
Coke Oven: pipe pulls wood logs and not the charcoal.
Blast Furnace:  the charcoal  is pulled out.

**Comment by wi-ta** [comment] 2015-06-10 19:35
This is the only way it does work
![2015-06-10_21 33 49](https://cloud.githubusercontent.com/assets/11215905/8092200/87775c96-0fb8-11e5-8d9a-9dd2fd1d4a01.png)

**Comment by multiplemonomials** [comment] 2015-06-10 19:45
I'm pretty sure that it's crashing because that Forestry version doesn't support Buildcraft 7.  Pretty much any crash log that talks about `CreativeTabBuildCraft` is because of a mod build for BC 6 being used with BC 7.

Also, the Gravity Feed Pipe pulls items out of the bottom slots of an inventory, whatever that may be.  What does it pull out if you put a wooden pipe and redstone engine on the bottom?

**Comment by wi-ta** [comment] 2015-06-10 19:56
"the Gravity Feed Pipe pulls items out of the bottom slots of an inventory"
Unfortunately not the iron ore is in a top slot and is pulled out.

"What does it pull out if you put a wooden pipe and redstone engine on the bottom?"
only the crushed ore from the bottom slot

**Comment by wi-ta** [comment] 2015-06-10 20:31
I found a new forestry version on jenkins that ist working with BC7.
Gravity Feed Pipe pull out everything.
![2015-06-10_22 27 39](https://cloud.githubusercontent.com/assets/11215905/8093255/2c9c821c-0fc0-11e5-82ef-af876d4d642a.png)

**Comment by multiplemonomials** [comment] 2015-06-11 06:52
I can reproduce the issue.  I'll look into it tomorrow.

**Comment by multiplemonomials** [comment] 2015-06-14 18:41
Alright, try https://www.dropbox.com/s/40pddsvxjhwirln/additionalpipes-4.6.0.jar?dl=0

**Comment by wi-ta** [comment] 2015-06-14 21:10
Working perfect now ,also with forestry an railcraft 
Great job :-)
Will this pipe be available for buildcraft-6.4.17 ?

![2015-06-14_23 05 40](https://cloud.githubusercontent.com/assets/11215905/8150430/fc7e0222-12e9-11e5-9b22-4125707e7407.png)

**Comment by wi-ta** [comment] 2015-06-14 21:16
I just did see the recipe.
May i suggest this recipe.
![recipe](https://cloud.githubusercontent.com/assets/11215905/8150456/3d42623e-12eb-11e5-9070-ef9b1cd16484.PNG)
This pipe is a replacement for a hopper and the hopper is 5 iron so 3 iron is ok i think

**Comment by multiplemonomials** [comment] 2015-06-25 02:11
I'm not planning on backporting it to Buildcraft 6.  Do you want me to?

I added your recipe.

Also, would you mind testing something for me?  It's the Jeweled Pipe, like a diamond pipe, but with 27 slots per side and the ability to filter based on metadata and NBT.  It's in [this version](https://www.dropbox.com/s/40pddsvxjhwirln/additionalpipes-4.6.0.jar?dl=0).  Thanks.

**Comment by wi-ta** [comment] 2015-06-30 17:27
Heya
I just did download 
My server runs on 6.4.17 so i can only test local.

**Comment by wi-ta** [comment] 2015-06-30 17:28
darn

**Comment by multiplemonomials** [comment] 2015-07-08 07:04
Oh, sorry, somehow I missed your response. I'll make a backported version with the Gravity Feed Pipe.  This texture error should be fixed in the release version.

**Closed** 2015-07-24 10:38 UTC
